apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: alaina-web
  namespace: alaina
  labels:
    app: alaina
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alaina
  template:
    metadata:
      labels:
        app: alaina
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "64Mi"
          volumeMounts:
            - name: site-content
              mountPath: /usr/share/nginx/html
              readOnly: true
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: site-content
          configMap:
            name: alaina-site-html
        - name: nginx-conf
          configMap:
            name: alaina-nginx-conf
